# Generated by Django 4.0.6 on 2024-06-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('skills', models.TextField(default='')),
                ('projects', models.TextField(default='')),
                ('cpi', models.IntegerField(default=9)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(default='unknown position', max_length=200),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resup.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resup.student')),
            ],
        ),
    ]
