# Generated by Django 4.0.6 on 2024-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0002_student_company_description_job_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branch',
            field=models.CharField(default='all', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='cpi',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
