# Generated by Django 4.0.6 on 2024-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0003_job_branch_job_cpi_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='suggestions',
            field=models.TextField(default='None.'),
        ),
    ]
