# Generated by Django 4.0.6 on 2024-06-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0004_application_resume_application_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
