# Generated by Django 4.0.6 on 2024-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0005_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
