# Generated by Django 4.0.6 on 2024-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0007_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='branch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='', max_length=200),
        ),
    ]
