# Generated by Django 4.0.6 on 2024-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0008_application_exp_job_exp_job_level_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='stack',
            field=models.TextField(default=''),
        ),
    ]
