# Generated by Django 4.0.6 on 2024-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0009_job_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='absent_skills',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='absent_stack',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='simscore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='skillscore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='techscore',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='cpi',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpi',
            field=models.FloatField(default=9),
        ),
    ]
