# Generated by Django 4.0.6 on 2024-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0010_application_absent_skills_application_absent_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stack',
            field=models.TextField(default=''),
        ),
    ]
