# Generated by Django 4.0.6 on 2024-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resup', '0011_student_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='example.pdf', upload_to=''),
        ),
    ]
